require "fileutils"
require "shellwords"
require "open3"

REPO_ROOT       = File.expand_path("../..", __dir__)
WORKSPACE_ROOT  = File.expand_path("..", REPO_ROOT)
ARTIFACTS_DIR   = File.expand_path("build", REPO_ROOT)
TIMESTAMP_TOKEN = Time.now.utc.strftime("%Y%m%d-%H%M%S")

# iOS (Native — generated by expo prebuild)
IOS_WORKSPACE = File.expand_path("ios/Baat.xcworkspace", REPO_ROOT)
IOS_XCODEPROJ = File.expand_path("ios/Baat.xcodeproj", REPO_ROOT)
IOS_SCHEME    = "Baat"
IOS_TEAM_ID   = "BZRTC4A75L"
IOS_IPA_ABS   = File.expand_path("build/ios-native.ipa", REPO_ROOT)

# Android (Native — generated by expo prebuild)
ANDROID_APP_DIR = File.expand_path("android/app", REPO_ROOT)
ANDROID_GRADLE  = File.expand_path("android/app/build.gradle", REPO_ROOT)
ANDROID_AAB_ABS = File.expand_path("build/app-native-release.aab", REPO_ROOT)
